///////////////////////////////////////////////////////////
//  CajasModel.cs
//  Implementation of the Class CajasModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:30
//  Original author: Ing. Alan Ortiz Pèrez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SiCGA.Clases.Modelos;
namespace SiCGA.Clases.Modelos {
	/// <summary>
	/// Modelo para la Tabla Cajas
	/// </summary>
	public class CajasModel {

		/// <summary>
		/// Propiedad de Identificaciòn de la Caja
		/// </summary>
		private int _id;
		/// <summary>
		/// Propiedad de identificador del nùmero de cajas
		/// </summary>
		private int _numero;
		/// <summary>
		/// Propiedad que nos indica el nùmero de folders/carpetas que contiene la caja
		/// </summary>
		private int _folders_carpetas;
		/// <summary>
		/// Propiedad que nos idica
		/// </summary>
		private int _año;
		/// <summary>
		/// Propiedad que indica que Nùmero de Caja de una Remesa pertenece
		/// </summary>
		private int _NdeM;
		/// <summary>
		/// Identificador de la Transferencia a la que pertenece la caja
		/// </summary>
		private TransferenciasModel _transferencia;

		public CajasModel(){

		}

		~CajasModel(){

		}

		/// <summary>
		/// Acceso a la Porpiedad Id
		/// </summary>
		public int Id{
            get { return _id; }
            set { _id = value; }
		}

		public int Numero{
            get { return _numero; }
            set { _numero = value; }
		}

		/// <summary>
		/// Acceso a la Propiedad Folders/Carpetas
		/// </summary>
		public int Folders_Carpetas{
            get { return _folders_carpetas; }
            set { _folders_carpetas = value; }
		}

		/// <summary>
		/// Acceso a la Propiedad del año de la transferencia de la caja
		/// </summary>
		public int Año{
            get { return _año; }
            set { _año = value; }
		}

		/// <summary>
		/// Acceso a la Propiedad de Paginaciòn de las Cajas
		/// </summary>
		public int NdeM{
            get { return _NdeM; }
            set { _NdeM = value; }
		}

		/// <summary>
		/// Acceso a la Propiedad Transferencia
		/// </summary>
		public TransferenciasModel Transferencia{
            get { return _transferencia; }
            set { _transferencia = value; }
		}

	}//end CajasModel

}//end namespace Modelos