///////////////////////////////////////////////////////////
//  ClasificacionesModel.cs
//  Implementation of the Class ClasificacionesModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:31
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace SiCGA.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Clasificaciones
	/// </summary>
	public class ClasificacionesModel {

		/// <summary>
		/// Identificador de la Clasificación
		/// </summary>
		private int _id;
		/// <summary>
		/// Descripción de la Clasificación
		/// </summary>
		private string _calsificacion;

		public ClasificacionesModel(){

		}
        /// <summary>
        /// Constructor de la Clase que Recibe Parámetros
        /// </summary>
        /// <param name="id">Identificador del Clasificación</param>
        /// <param name="clasi">Descripción de la Clasificación</param>
        public ClasificacionesModel(int id, string clasi)
        {
            this.Id = id;
            this.Clasificacion = clasi;
		}

		~ClasificacionesModel(){

		}

		/// <summary>
		/// Acceder a la Propiedad ID
		/// </summary>
		public int Id{
            get { return _id; }
            set { _id = value; }
		}

		/// <summary>
		/// Acceder ala Propiedad Clasificación
		/// </summary>
		public string Clasificacion{
            get { return _calsificacion; }
            set { _calsificacion = value; }
		}

	}//end ClasificacionesModel

}//end namespace Modelos