///////////////////////////////////////////////////////////
//  FondosModel.cs
//  Implementation of the Class FondosModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:35
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace SiCGA.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Fondos
	/// </summary>
	public class FondosModel {

		/// <summary>
		/// Descripción del Fondo
		/// </summary>
		private string _fondo;
		/// <summary>
		/// Identificador del Fondo
		/// </summary>
		private int _id;

		public FondosModel(){

		}

		/// 
		/// <param name="id">Identificador del Fondo</param>
		/// <param name="fondo">Descripción del Fondo</param>
		public FondosModel(int id, string fondo){
            this.Id = id;
            this.Fondo = fondo;
		}

		~FondosModel(){

		}
        /// <summary>
        /// Acceder a la Propiedad Fondo
        /// </summary>
		public string Fondo{
            get { return _fondo; }
            set { _fondo = value; }
		}
        /// <summary>
        /// Acceder a la Propiedad Id
        /// </summary>
		public int Id{
            get { return _id; }
            set { _id = value; }
		}

	}//end FondosModel

}//end namespace Modelos