///////////////////////////////////////////////////////////
//  FondosModel.cs
//  Implementation of the Class FondosModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:35
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace SiCGA.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Fondos
	/// </summary>
	public class FondosModel {

		/// <summary>
		/// Descripción del Fondo
		/// </summary>
		private string _fondo;
		/// <summary>
		/// Identificador del Fondo
		/// </summary>
		private int _id;

		public FondosModel(){

		}

		/// 
		/// <param name="id"></param>
		/// <param name="fondo"></param>
		public FondosModel(int id, string fondo){

		}

		~FondosModel(){

		}

		public int Fondo{
			get;
			set;
		}

		public int Id{
			get;
			set;
		}

	}//end FondosModel

}//end namespace Modelos