///////////////////////////////////////////////////////////
//  RegistrosModel.cs
//  Implementation of the Class RegistrosModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:51
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SiCGA.Clases.Modelos;
namespace SiCGA.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Registros
	/// </summary>
	public class RegistrosModel {

		/// <summary>
		/// Identificador del Registro
		/// </summary>
		private int _id;
		/// <summary>
		/// Serie Documental de los Documentos
		/// </summary>
		private string _seriedoctal;
		/// <summary>
		/// Fondo del Documento
		/// </summary>
		private FondosModel _fondo;
		/// <summary>
		/// SubFondo del Documento
		/// </summary>
		private SubFondosModel _subfondo;
		/// <summary>
		/// Fecha de Apertura de la Serie Documental
		/// </summary>
		private DateTime _fechainicio;
		/// <summary>
		/// Fecha del cierre de la Serie Documental
		/// </summary>
		private DateTime _fechacierre;
		/// <summary>
		/// Propiedad que contiene el nombre del expediente
		/// </summary>
		private string _nombreexp;
		/// <summary>
		/// Propiedad con la descripción del expediente
		/// </summary>
		private string _descripcion;
		/// <summary>
		/// Propiedad con el número de hojas del expediente
		/// </summary>
		private int _numhojas;
		/// <summary>
		/// Propiedad con la Clave Sevie del Expediente
		/// </summary>
		private string _cvesevi;
		/// <summary>
		/// Propiedad con la identificación del Valor Documental del Expediente
		/// </summary>
		private ValoresDoctalesModel _valordoctal;
		/// <summary>
		/// Propiedad con la Clasificación del Expedente
		/// </summary>
		private ClasificacionesModel _clasificacion;
		/// <summary>
		/// Propiedad con la Valoración Documental del Expediente
		/// </summary>
		private ValoracionDoctalModel _valoraciondoctal;
		/// <summary>
		/// Propiedad con Otra Información acerca del expediente
		/// </summary>
		private string _otrainfo;
		/// <summary>
		/// Propiedad con el estatus del expediente
		/// </summary>
		private bool _estatus;

		/// <summary>
		/// Constructor del Modelo
		/// </summary>
		public RegistrosModel(){

		}

		~RegistrosModel(){

		}

		/// <summary>
		/// Acceder a la Propiedad de Identificador
		/// </summary>
		public int Id{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Serie Documental
		/// </summary>
		public string SerieDoctal{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Fondo
		/// </summary>
		public FondosModel Fondo{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad SubFondo
		/// </summary>
		public SubFondosModel SubFondo{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Fecha de Inicio
		/// </summary>
		public DateTime FechaInicio{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Fecha de Cierre
		/// </summary>
		public DateTime FechaCierre{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Nombre de Expediente
		/// </summary>
		public string NombreExp{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Descripción
		/// </summary>
		public string Descripcion{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la propiedad Número de Hojas
		/// </summary>
		public int NumHojas{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Clave Sevi
		/// </summary>
		public string CveSevi{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Valor Documental
		/// </summary>
		public ValoresDoctalesModel ValorDoctal{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Clasificación
		/// </summary>
		public ClasificacionesModel Clasificacion{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Valoracion Documental
		/// </summary>
		public ValoracionDoctalModel ValoracionDoctal{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Otra Información
		/// </summary>
		public string OtraInfo{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Estatus
		/// </summary>
		public bool Estatus{
			get;
			set;
		}

	}//end RegistrosModel

}//end namespace Modelos