///////////////////////////////////////////////////////////
//  SeccionesModel.cs
//  Implementation of the Class SeccionesModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:55
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace SiCGA.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Secciones
	/// </summary>
	public class SeccionesModel {

		private int _id;
		private string _seccion;

		public SeccionesModel(){

		}

		/// <summary>
		/// Constructor de la Clase que recibe dos parámetros
		/// </summary>
		/// <param name="id"></param>
		/// <param name="secc"></param>
		public SeccionesModel(int id, string secc){

		}

		~SeccionesModel(){

		}

		/// <summary>
		/// Acceder a la Propiedad Id
		/// </summary>
		public int Id{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Sección
		/// </summary>
		public int Seccion{
			get;
			set;
		}

	}//end SeccionesModel

}//end namespace Modelos