///////////////////////////////////////////////////////////
//  SeriesModel.cs
//  Implementation of the Class SeriesModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:57
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SiCGA.Clases.Modelos;
namespace SiCGA.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Series
	/// </summary>
	public class SeriesModel {

		/// <summary>
		/// Identificador, llave
		/// </summary>
		private int _id;
		/// <summary>
		/// Identificador de la Serie
		/// </summary>
		private int _idserie;
		/// <summary>
		/// Identificador de la Sección
		/// </summary>
		private SeccionesModel _seccion;
		/// <summary>
		/// Descripción de la Serie
		/// </summary>
		private string _serie;

		public SeriesModel(){

		}

		/// <summary>
		/// Constructor que recibe Parámetros
		/// </summary>
		/// <param name="idserie"></param>
		/// <param name="serie"></param>
		/// <param name="seccion"></param>
		public SeriesModel(int idserie, string serie, SeccionesModel seccion){

		}

		~SeriesModel(){

		}

		/// <summary>
		/// Acceder a la llave de la Serie
		/// </summary>
		public int Id{
			get;
			set;
		}

		/// <summary>
		/// Acceder al Identificador de la Serie
		/// </summary>
		public int IdSerie{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Sección
		/// </summary>
		public SeccionesModel Seccion{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la Propiedad Serie
		/// </summary>
		public string Serie{
			get;
			set;
		}

	}//end SeriesModel

}//end namespace Modelos