///////////////////////////////////////////////////////////
//  UnidadesAdmvasModel.cs
//  Implementation of the Class UnidadesAdmvasModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:19:07
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace SiCGA.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla UnidadesAdmvas
	/// </summary>
	public class UnidadesAdmvasModel {

		private int _id;
		private string _unidad;

		public UnidadesAdmvasModel(){

		}

		~UnidadesAdmvasModel(){

		}

		/// <summary>
		/// Acceder a la Propiedad Id
		/// </summary>
		public int Id{
			get;
			set;
		}

		/// <summary>
		/// Acceder a la propiedad Unidad
		/// </summary>
		public string Unidad{
			get;
			set;
		}

	}//end UnidadesAdmvasModel

}//end namespace Modelos