///////////////////////////////////////////////////////////
//  ValoracionDoctalModel.cs
//  Implementation of the Class ValoracionDoctalModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:19:12
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace SiCGA.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla ValoracionDoctal
	/// </summary>
	public class ValoracionDoctalModel {

		private int _id;
		private string _valoracion;

		public ValoracionDoctalModel(){

		}

		/// <summary>
        /// Cobstructor de la Clase que recibe parámetros
        /// </summary>
        /// <param name="id"></param>
        /// <param name="valoracion"></param>
		public ValoracionDoctalModel(int id, string valoracion){

            this.Id = id;
            this.Valoracion = valoracion;
		}

		~ValoracionDoctalModel(){

		}
        /// <summary>
        /// Acceder a la Propiedad Id
        /// </summary>
		public int Id{
            get { return _id; }
            set { _id = value; }
		}
        /// <summary>
        /// Acceder a la Propiedad Valoración
        /// </summary>
		public string Valoracion{
            get { return _valoracion; }
            set { _valoracion = value; }
		}

	}//end ValoracionDoctalModel

}//end namespace Modelos