///////////////////////////////////////////////////////////
//  ValoracionDoctalModel.cs
//  Implementation of the Class ValoracionDoctalModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:19:12
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace SiCGA.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla ValoracionDoctal
	/// </summary>
	public class ValoracionDoctalModel {

		private int _id;
		private string _valoracion;

		public ValoracionDoctalModel(){

		}

		/// 
		/// <param name="id"></param>
		/// <param name="valoracion"></param>
		public ValoracionDoctalModel(int id, string valoracion){

		}

		~ValoracionDoctalModel(){

		}

		public int Id{
			get;
			set;
		}

		public string Valoracion{
			get;
			set;
		}

	}//end ValoracionDoctalModel

}//end namespace Modelos