///////////////////////////////////////////////////////////
//  Conexion.cs
//  Implementation of the Class Conexion
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:31
//  Original author: Elizabeth
///////////////////////////////////////////////////////////

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Text;
using System.IO;
using DatosBD;



namespace SiCGA.Clases
{
    public class Conexion
    {

        private SqlDataAdapter _adapter;
        private SqlCommand _command;
        private SqlConnection _connection;
        private string _error;
        private DataTable _tabla;

        /// <summary>
        /// Contructor Interno para Inicializar la Conexión a la Base de Datos
        /// </summary>
        protected Conexion()
        {
            _connection = new SqlConnection("Server =" + DatosUsuarios.Servidor + "; Initial Catalog =" + DatosUsuarios.BaseDeDatos + ";Persist Security Info=False;Integrated Security=true;");
        }

        ~Conexion()
        {

        }

        /// <summary>
        /// Método Público para Establecer la Conexión a la Base de Datos
        /// </summary>
        /// <returns>valor Boleano</returns>
        public bool Abrir()
        {
            if (Connection.State == ConnectionState.Closed)
            {
                try
                {
                    Connection.Open();
                    return true;
                }
                catch (SqlException e)
                {
                    Error = e.Message.ToString();
                    return false;
                }
            }
            else
            { return false; }
        }

        /// <summary>
        /// Acceder de manera interna al Adaptador
        /// </summary>
        private SqlDataAdapter Adapter
        {
            get { return _adapter; }
            set { _adapter = value; }
        }

        /// <summary>
        /// Método Público para Cerrar la Coenxión de la Base de Datos
        /// </summary>
        public bool Cerrar()
        {
            if (Connection.State == ConnectionState.Open)
            {
                try
                {
                    Connection.Close();
                    return true;
                }
                catch (SqlException e)
                {
                    Error = e.Message.ToString();
                    return false;
                }
            }
            else
            { return false; }
        }

        /// <summary>
        /// Acceder de manera interna al comando
        /// </summary>
        private SqlCommand Command
        {
            get { return _command; }
            set { _command = value; }
        }

        /// <summary>
        /// Acceder de manera interna a la Conexion
        /// </summary>
        private SqlConnection Connection
        {
            get { return _connection; }
        }

        /// <summary>
        /// Método para Realizar Consultas a través de Procedimientos Almacenados
        /// </summary>
        /// <param name="procedimiento">Nombre del Procedimiento</param>
        /// <param name="lista">Arreglo con Parámetros SQL</param>
        protected bool ConsultarProcedimiento(string procedimiento, List<Parametros> lista)
        {
            Command = new SqlCommand();
            Command.CommandType = CommandType.StoredProcedure;
            Command.CommandText = procedimiento;
            Command.Connection = Connection;
            foreach (Parametros p in lista)
            {
                Command.Parameters.AddWithValue(p.NombreParametro, p.ValorParametro);
            }
            Tabla = new DataTable();
            Adapter = new SqlDataAdapter();
            Adapter.SelectCommand = Command;
            Command.ExecuteNonQuery();
            Adapter.Fill(Tabla);
            return true;
        }

        /// <summary>
        /// Mira Rafita... este es el Método para Ejecutar Procedimientos Almacenados
        /// </summary>
        /// <param name="procedimiento">Nombre del Procedimiento</param>
        /// <param name="lista">Arreglo de Parámetros de SQL</param>
        protected bool EjecutarProcedimiento(string procedimiento, List<Parametros> lista)
        {

            return false;
        }

        /// <summary>
        /// Acceder al Error que resulte en los intentos de conexion
        /// </summary>
        public string Error
        {
            get;
            set;
        }

        /// <summary>
        /// Acceder a los datos alojados en la tabla
        /// </summary>
        public DataTable Tabla
        {
            get;
            set;
        }

    }//end Conexion

}//end namespace SiCGA.Clases