///////////////////////////////////////////////////////////
//  MovinientosController.cs
//  Implementation of the Class MovinientosController
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:45
//  Original author: Ing. Alan Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Clases;
namespace Clases.Controladores {
	public class MovinientosController : Metodos {

		public MovinientosController(){

		}

		~MovinientosController(){

		}

		/// <summary>
		/// Método Para Actualizar los Registros
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo class</param>
		public override bool ActualizarRegistro(Object o){

			return false;
		}

		/// <summary>
		/// Método Para Consultar un Registro
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo class</param>
		public override bool ConsultarRegistro(Object o){

			return false;
		}

		/// <summary>
		/// Método para Consultar Todos los Registros
		/// </summary>
		/// <returns>Boleano</returns>
		public override bool ConsultarRegistros(){

			return false;
		}

		/// <summary>
		/// Método para Ingresar un Registro
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo Class</param>
		public override bool IngresarRegisto(Object o){

			return false;
		}

	}//end MovinientosController

}//end namespace Controladores