///////////////////////////////////////////////////////////
//  UnidadesAdmvasController.cs
//  Implementation of the Class UnidadesAdmvasController
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:19:05
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SiCGA.Clases;
namespace SiCGA.Clases.Controladores {
	/// <summary>
	/// Controlador del Modelo UnidadesAdmvas
	/// </summary>
	public class UnidadesAdmvasController : Metodos {

		public UnidadesAdmvasController(){

		}

		~UnidadesAdmvasController(){

		}

		/// 
		/// <param name="o"></param>
		public override bool ActualizarRegistro(object o){

			return false;
		}

		/// 
		/// <param name="o"></param>
		public override bool ConsultarRegistro(object o){

			return false;
		}

		public override bool ConsultarRegistros(){

			return false;
		}

		/// 
		/// <param name="o"></param>
		public override bool IngresarRegisto(object o){

			return false;
		}

	}//end UnidadesAdmvasController

}//end namespace Controladores