///////////////////////////////////////////////////////////
//  Metodos.cs
//  Implementation of the Class Metodos
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:41
//  Original author: Ing. Alan Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace SiCGA.Clases {
	public abstract class Metodos : Conexion {

		public Metodos(){

		}

		~Metodos(){

		}

		/// <summary>
		/// Método Para Actualizar los Registros
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo class</param>
		public abstract bool ActualizarRegistro(Object o);

		/// <summary>
		/// Método Para Consultar un Registro
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo class</param>
		public abstract bool ConsultarRegistro(Object o);

		/// <summary>
		/// Método para Consultar Todos los Registros
		/// </summary>
		/// <returns>Boleano</returns>
		public abstract bool ConsultarRegistros();

		/// <summary>
		/// Método para Ingresar un Registro
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo Class</param>
		public abstract bool IngresarRegisto(Object o);

	}//end Metodos

}//end namespace SiCGA.Clases