///////////////////////////////////////////////////////////
//  Parametros.cs
//  Implementation of the Class Parametros
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:48
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace SADI.Clases {
	public class Parametros {

		private string _nomparam;
		private string _valparam;

		public Parametros(){

		}

		/// <summary>
		/// Constructor que recibe Parámetros
		/// </summary>
		/// <param name="nombre">Nombre del Parámetro</param>
		/// <param name="valor">Valor del Parámetro</param>
		public Parametros(string nombre, string valor){
            NombreParametro = nombre;
            ValorParametro = valor;
		}

		/// <summary>
		/// Asignar el Nombre del Parámetro
		/// </summary>
		public string NombreParametro{
			get { return _nomparam; }
            set { _nomparam = value; }
		}

		/// <summary>
		/// Asignar el Valor del Parámetro
		/// </summary>
		public string ValorParametro{
            get { return _valparam; }
            set { _valparam = value; }
		}

	}//end Parametros

}//end namespace SADI.Clases
