///////////////////////////////////////////////////////////
//  BitacoraModel.cs
//  Implementation of the Class BitacoraModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:29
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SADI.Clases.Modelos;
namespace SADI.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Bitácora
	/// </summary>
	public class BitacoraModel {

		/// <summary>
		/// Propiedad Identificadora del registro en la Bitácora
		/// </summary>
		private int _id;
		/// <summary>
		/// Propiedad de identificación de la serie documental
		/// </summary>
		private RegistrosModel _registro = new RegistrosModel();
		/// <summary>
		/// Propiedad de la Fecha del Movimiento
		/// </summary>
		private DateTime _fecha;
		/// <summary>
		/// Propiedad de identificación del movimiento realizado
		/// </summary>
		private MovimientosModel _movimiento = new MovimientosModel();
		/// <summary>
		/// Propiedad del Usuario que realizò el movieminto
		/// </summary>
		private UsuariosModel _usuario = new UsuariosModel();
		/// <summary>
		/// Propiedad del Nombre de la Computadora desde dónde se realizó el movimiento
		/// </summary>
		private string _computadora;
		/// <summary>
		/// Propiedad de la IP desde dónde se realizó el movimiento
		/// </summary>
		private string _idcomputadora;
        /// <summary>
        /// Propiedad de la Mac Address de la computadora desde dónde se realizó el moviemiento
        /// </summary>
        private string _macaddress;

        /// <summary>
        /// Constructor de la clase
        /// </summary>
		public BitacoraModel(){

		}
        /// <summary>
        /// Destructor de la Clase
        /// </summary>
		~BitacoraModel(){

		}
        /// <summary>
        /// Constructor de la Clase que recibe parámetros
        /// </summary>
        /// <param name="id">Identificador del Modelo</param>
        /// <param name="seriedoc">Serie Documental del Modelo</param>
        /// <param name="fec">Fecha del Movimiento en el Modelo</param>
        /// <param name="mov">Movimiento en el Modelo</param>
        /// <param name="usr">Usuario que realizó el Movimiento</param>
        /// <param name="comp">Computadora desde dónde se realizó el movimiento</param>
        /// <param name="idcomp">identificador de la computadora desde dónde se realizó el movimiento</param>
        public BitacoraModel(int id, RegistrosModel registro, DateTime fec, MovimientosModel mov,
            UsuariosModel usr, string comp, string idcomp, string macadd)
        {
            this.Id = id;
            this.Registro = registro;
            this.Fecha = fec;
            this.Movimiento = mov;
            this.Usuario = usr;
            this.Computadora = comp;
            this.IdComputadora = idcomp;
        }

		/// <summary>
		/// Acceso a la Propiedad Identificación del movimiento
		/// </summary>
		public int Id{
            get { return _id; }
            set { _id = value; }
		}
        /// <summary>
        /// Acceso a la Propiedad SerieDoctal
        /// </summary>
		public RegistrosModel Registro{
            get { return _registro; }
            set { _registro = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Fecha del Movimiento
		/// </summary>
		public DateTime Fecha{
            get { return _fecha; }
            set { _fecha = value; }
		}

		/// <summary>
		/// Acceso a la propiedad Moviemiento
		/// </summary>
		public MovimientosModel Movimiento{
            get { return _movimiento; }
            set { _movimiento = value; }
		}

		/// <summary>
		/// Acceso a la Propiedad Usuario
		/// </summary>
		public UsuariosModel Usuario{
            get { return _usuario; }
            set { _usuario = value; }
		}

		/// <summary>
		/// Acceso a la Propiedad Computadora
		/// </summary>
		public string Computadora{
            get { return _computadora; }
            set { _computadora = value; }
		}

		/// <summary>
		/// Acceso a la Propiedad de Identificaciòn de la Computadora
		/// </summary>
		public string IdComputadora{
            get { return _idcomputadora; }
            set { _idcomputadora = value; }
		}
        /// <summary>
        /// Acceso a la Propiedad MacAddress del Modelo
        /// </summary>
        public string MacAddress
        {
            get { return _macaddress; }
            set { _macaddress = value; }
        }

	}//end BitacoraModel

}//end namespace Modelos