///////////////////////////////////////////////////////////
//  DigitalizacionesModel.cs
//  Implementation of the Class DigitalizacionesModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:33
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SADI.Clases.Modelos;
namespace SADI.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Digitalizaciones
	/// </summary>
	public class DigitalizacionesModel {

		/// <summary>
		/// Propiedad que identifica el movimiento de digitalización
		/// </summary>
		private int _id;
		/// <summary>
		/// Propiedad que representa el código de la serie documental del documento
		/// </summary>
		private RegistrosModel _seriedoctal = new RegistrosModel();
        /// <summary>
        /// Propiedad del Nombre del Documento
        /// </summary>
        private string _nombredoc;
		/// <summary>
		/// Propiedad que representa al digitalización del documento
		/// </summary>
		private byte [] _documento;
		/// <summary>
		/// Propiedad que representa el folio del documento
		/// </summary>
		private int _folio;
        /// <summary>
        /// Propiedad de la Extensión del Documento
        /// </summary>
        private string _extension;
        /// <summary>
        /// Propiedad del Tamaño del Documento
        /// </summary>
        private int _tamaño;

        /// <summary>
        /// Constructo Vacio
        /// </summary>
		public DigitalizacionesModel(){

		}

		/// <summary>
        /// Constructor de la Clase
        /// </summary>
        /// <param name="id">Identificador del Documento</param>
        /// <param name="seried">Serie Documental del Documento</param>
        /// <param name="nombredoc">Nombre del Documento</param>
        /// <param name="doc">Documento en byte[]</param>
        /// <param name="folio">Folio del Documento</param>
        /// <param name="ext">Extensión del Documento</param>
        /// <param name="size">Tamaño del Documento</param>
		public DigitalizacionesModel(int id, RegistrosModel seried,string nombredoc, byte[] doc, int folio,string ext,int size){
            this.Id = id;
            this.SDoctal = seried;
            this.NombreDoc = nombredoc;
            this.Documento = doc;
            this.Folio = folio;
            this.Extension = ext;
            this.Tamaño = size;
		}
        /// <summary>
        /// Destructor de la Clase
        /// </summary>
		~DigitalizacionesModel(){

		}

		/// <summary>
		/// Acceder a la propiedad Id
		/// </summary>
		public int Id{
			get { return _id; }
            set { _id = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad que aloja la serie documental
		/// </summary>a
		public RegistrosModel SDoctal{
            get { return _seriedoctal; }
            set { _seriedoctal = value; }
		}

        /// <summary>
        /// Acceder a la Propiedad Nombre del Documento
        /// </summary>
        public string NombreDoc
        { get { return _nombredoc; } set { _nombredoc = value; } }

		/// <summary>
		/// Acceder a la Propiedad del Documento digitalizado
		/// </summary>
		public byte[] Documento{
            get { return _documento; }
            set { _documento = value; }
		}

		/// <summary>
		/// Acceder a la propiedad del Folio del Documento
		/// </summary>
		public int Folio{
            get { return _folio; }
            set { _folio = value; }
		}

        /// <summary>
        /// Acceder a la Propiedad de la Extensión del Documento
        /// </summary>
        public string Extension
        { get { return _extension; } set { _extension = value; } }

        /// <summary>
        /// Acceder a la Propiedad del Tamaño del Documento
        /// </summary>
        public int Tamaño
        { get { return _tamaño; } set { _tamaño = value; } }

	}//end DigitalizacionesModel

}//end namespace Modelos