///////////////////////////////////////////////////////////
//  MovimientosModel.cs
//  Implementation of the Class MovimientosModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:43
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace SiCGA.Clases.Modelos {
	/// <summary>
	/// Modelo de la Table Movimientos
	/// </summary>
	public class MovimientosModel {

		/// <summary>
		/// Identificador del Movimiento
		/// </summary>
		private int _id;
		/// <summary>
		/// Descripción del Movimiento
		/// </summary>
		private string _movimiento;

		public MovimientosModel(){

		}

		/// <summary>
		/// Constructor de la Clase que recibe Parámetros
		/// </summary>
		/// <param name="id">Identificador del Modelo</param>
		/// <param name="mov">Descripción del Movimiento</param>
		public MovimientosModel(int id, string mov){
            this.Id = id;
            this.Movimiento = mov;
		}

		~MovimientosModel(){

		}

		/// <summary>
		/// Acceder a la Propiedad ID
		/// </summary>
		public int Id{
            get { return _id; }
            set { _id = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Movimiento
		/// </summary>
		public string Movimiento{
            get { return _movimiento; }
            set { _movimiento = value; }
		}

	}//end MovimientosModel

}//end namespace Modelos