///////////////////////////////////////////////////////////
//  RegistrosModel.cs
//  Implementation of the Class RegistrosModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:51
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SADI.Clases.Modelos;
namespace SADI.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Registros
	/// </summary>
	public class RegistrosModel {

		/// <summary>
		/// Serie Documental de los Documentos
		/// </summary>
		private string _seriedoctal;
        /// <summary>
        /// Tema de la Serie Documental
        /// </summary>
        private TemasModel _tema = new TemasModel();
        /// <summary>
        /// Fondo del Documento
        /// </summary>
        private FondosModel _fondo = new FondosModel();
		/// <summary>
		/// SubFondo del Documento
		/// </summary>
		private SubFondosModel _subfondo = new SubFondosModel();
		/// <summary>
		/// Fecha de Apertura de la Serie Documental
		/// </summary>
		private DateTime _fechainicio;
		/// <summary>
		/// Fecha del cierre de la Serie Documental
		/// </summary>
		private DateTime? _fechacierre;
		/// <summary>
		/// Propiedad con la descripción del expediente
		/// </summary>
		private string _descripcion;
		/// <summary>
		/// Propiedad con el número de hojas del expediente
		/// </summary>
		private int _numhojas;
		/// <summary>
		/// Propiedad con la Clave Sevie del Expediente
		/// </summary>
		private string _cvesevi;
		/// <summary>
		/// Propiedad con la identificación del Valor Documental del Expediente
		/// </summary>
		private ValoresDoctalesModel _valordoctal = new ValoresDoctalesModel();
		/// <summary>
		/// Propiedad con la Clasificación del Expedente
		/// </summary>
		private ClasificacionesModel _clasificacion = new ClasificacionesModel();
		/// <summary>
		/// Propiedad con Otra Información acerca del expediente
		/// </summary>
		private string _otrainfo;
		/// <summary>
		/// Propiedad con el estatus del expediente
		/// </summary>
		private bool _estatus;

		/// <summary>
		/// Constructor del Modelo
		/// </summary>
		public RegistrosModel(){

		}

		~RegistrosModel(){

		}


		/// <summary>
		/// Acceder a la Propiedad Serie Documental
		/// </summary>
		public string SerieDoctal{
			get { return _seriedoctal; }
            set { _seriedoctal = value; }
		}

        /// <summary>
        /// Acceder a la Propiedad Tema de la Serie Documental
        /// </summary>
        public TemasModel Tema
        { get { return _tema; }set { _tema = value; } }

		/// <summary>
		/// Acceder a la Propiedad Fondo
		/// </summary>
		public FondosModel Fondo{
            get { return _fondo; }
            set { _fondo = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad SubFondo
		/// </summary>
		public SubFondosModel SubFondo{
            get { return _subfondo; }
            set { _subfondo = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Fecha de Inicio
		/// </summary>
		public DateTime FechaInicio{
            get { return _fechainicio; }
            set { _fechainicio = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Fecha de Cierre
		/// </summary>
		public DateTime? FechaCierre{
            get { return _fechacierre; }
            set { _fechacierre = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Descripción
		/// </summary>
		public string Descripcion{
			get { return _descripcion; }
            set { _descripcion = value; }
		}

		/// <summary>
		/// Acceder a la propiedad Número de Hojas
		/// </summary>
		public int NumHojas{
            get { return _numhojas; }
            set { _numhojas = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Clave Sevi
		/// </summary>
		public string CveSevi{
            get { return _cvesevi; }
            set { _cvesevi = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Valor Documental
		/// </summary>
		public ValoresDoctalesModel ValorDoctal{
            get { return _valordoctal; }
            set { _valordoctal = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Clasificación
		/// </summary>
		public ClasificacionesModel Clasificacion{
            get { return _clasificacion; }
            set { _clasificacion = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Otra Información
		/// </summary>
		public string OtraInfo{
            get { return _otrainfo; }
            set { _otrainfo = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Estatus
		/// </summary>
		public bool Estatus{
            get { return _estatus; }
            set { _estatus = value; }
		}

	}//end RegistrosModel

}//end namespace Modelos