///////////////////////////////////////////////////////////
//  SeccionesModel.cs
//  Implementation of the Class SeccionesModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:55
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace SADI.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Secciones
	/// </summary>
	public class SeccionesModel {

		private string _id;
		private string _seccion;
        /// <summary>
        /// Construcrtor de la Clase que no recibe parámetros
        /// </summary>
		public SeccionesModel(){

		}

		/// <summary>
		/// Constructor de la Clase que recibe dos parámetros
		/// </summary>
		/// <param name="id"></param>
		/// <param name="secc"></param>
		public SeccionesModel(string id, string secc){
            this.Id = id;
            this.Seccion = secc;
		}
        /// <summary>
        /// Destructor de la Clase
        /// </summary>
		~SeccionesModel(){

		}

		/// <summary>
		/// Acceder a la Propiedad Id
		/// </summary>
		public string Id{
            get { return _id; }
            set { _id = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Sección
		/// </summary>
		public string Seccion{
            get { return _seccion; }
            set { _seccion = value; }
		}

	}//end SeccionesModel

}//end namespace Modelos