///////////////////////////////////////////////////////////
//  UsuariosModel.cs
//  Implementation of the Class UsuariosModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:19:11
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SADI.Clases.Modelos;
namespace SADI.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Usuarios
	/// </summary>
	public class UsuariosModel {

		
		private string _contraseña;//Contraseña del Usuario
		private bool _estatus;// Estatus del Usuario
		private int _id;// Identificador del Usuario
		private JerarquiasModel _jerarquia = new JerarquiasModel();
        private FondosModel _fondo = new FondosModel();
        private SubFondosModel _subfondo = new SubFondosModel();
        private DepartamentosModel _departamento = new DepartamentosModel();
        private AreasMedicasModel _areamedica = new AreasMedicasModel();
        private SubAreasModel _subarea = new SubAreasModel();
        private ServiciosModel _servicio = new ServiciosModel();
		private string _materno;
		private string _nombre;
		private string _paterno;
        private string _email;
		private string _usuario;
        private bool _atributos;

		/// <summary>
		/// Constructor de la Clase
		/// </summary>
		/// <param name="u">Objeto del Tipo Usuarios</param>
		public UsuariosModel(UsuariosModel u){
         
		}
        /// <summary>
        /// Constructor de la Clase
        /// </summary>
		public UsuariosModel(){

		}
        /// <summary>
        /// Destructor de la Clase
        /// </summary>
		~UsuariosModel(){

		}

		/// <summary>
		/// Acceder a la Propiedad Contraseña
		/// </summary>
		public string Contraseña{
			get { return _contraseña; }
            set { _contraseña = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Estatus
		/// </summary>
		public bool Estatus{
			get { return _estatus; }
            set { _estatus = value; }
		}
		/// <summary>
		/// Acceder a la identificación del Usuario
		/// </summary>
		public int Id{
			get { return _id; }
            set { _id = value; }
		}
		/// <summary>
		/// Acceder a la Propiedad Jerarquia
		/// </summary>
		public JerarquiasModel Jerarquia{
			get { return _jerarquia; }
			set { _jerarquia = value; }
		}
		/// <summary>
		/// Acceder a la Propiedad Apellido Materno
		/// </summary>
		public string Materno{
			get { return _materno; }
			set { _materno = value; }
		}
		/// <summary>
		/// Acceder a la Propiedad Nombre del Usuario
		/// </summary>
		public string Nombre{
			get { return _nombre; }
            set { _nombre = value; }
		}
		/// <summary>
		/// Acceder a la Propiedad Apellido Paterno
		/// </summary>
		public string Paterno{
			get { return _paterno; }
            set { _paterno = value; }
		}
		/// <summary>
		/// Acceder a la propiedad Usuario
		/// </summary>
		public string Usuario{
			get { return _usuario; }
			set { _usuario = value; }
		}
        /// <summary>
        /// Acceso a la Propiedad Fondo
        /// </summary>
        public FondosModel Fondo
        {
            get { return _fondo; }
            set { _fondo = value; }
        }
        /// <summary>
        /// Acceso a la Propiedad SubFondo
        /// </summary>
        public SubFondosModel SubFondo
        {
            get { return _subfondo; }
            set { _subfondo = value; }
        }
        /// <summary>
        /// Acceso a la Propiedad Departamento
        /// </summary>
        public DepartamentosModel Departamento
        { get { return _departamento; } set { _departamento = value; } }
        /// <summary>
        /// Acceso a la Propiedad Area Médica
        /// </summary>
        public AreasMedicasModel AreaMedica
        { get { return _areamedica; } set { _areamedica = value; } }
        /// <summary>
        /// Acceso a la Propiedad SubArea Médica
        /// </summary>
        public SubAreasModel SubArea
        { get { return _subarea; } set { _subarea = value; } }
        /// <summary>
        /// Acceso a la Propiedad Servicio
        /// </summary>
        public ServiciosModel Servicio
        { get { return _servicio; } set { _servicio = value; } }
        /// <summary>
        /// Acceso a la Propiedad Email
        /// </summary>
        public string Email
        {
            get { return _email; }
            set { _email = value; }
        }
        /// <summary>
        /// Acceso ala Propiedad Atributos
        /// </summary>
        public bool Atributos
        {
            get { return _atributos; }
            set { _atributos = value; }
        }
        
	}//end UsuariosModel

}//end namespace Modelos