///////////////////////////////////////////////////////////
//  UsuariosModel.cs
//  Implementation of the Class UsuariosModel
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:19:11
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SADI.Clases.Modelos;
namespace SADI.Clases.Modelos {
	/// <summary>
	/// Modelo de la Tabla Usuarios
	/// </summary>
	public class UsuariosModel {

		
		private string _contraseña;
		private bool _estatus;
		private int _id;
		private JerarquiasModel _jerarquia;
		private string _materno;
		private string _nombre;
		private string _paterno;
		private UnidadesAdmvasModel _unidadAdmva;
		private FondosModel _fondo;
		private SubFondosModel _subfondo;
		private string _usuario;

		/// <summary>
		/// Constructor de la Clase
		/// </summary>
		/// <param name="u">Objeto del Tipo Usuarios</param>
		public UsuariosModel(UsuariosModel u){

		}

		public UsuariosModel(){

		}

		~UsuariosModel(){

		}
		

		/// <summary>
		/// Acceder a la Propiedad Contraseña
		/// </summary>
		public string Contraseña{
			get { return _contraseña; }
            set { _contraseña = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Estatus
		/// </summary>
		public bool Estatus{
			get { return _estatus; }
            set { _estatus = value; }
		}

		/// <summary>
		/// Acceder a la identificación del Usuario
		/// </summary>
		public int Id{
			get { return _id; }
            set { _id = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Jerarquia
		/// </summary>
		public JerarquiasModel Jerarquia{
			get { return _jerarquia; }
			set { _jerarquia = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Apellido Materno
		/// </summary>
		public string Materno{
			get { return _materno; }
			set { _materno = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Nombre del Usuario
		/// </summary>
		public string Nombre{
			get { return _nombre; }
            set { _nombre = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Apellido Paterno
		/// </summary>
		public string Paterno{
			get { return _paterno; }
            set { _paterno = value; }
		}

		/// <summary>
		/// Acceder a la Propiedad Unidad Administrativa
		/// </summary>
		public UnidadesAdmvasModel UnidadAdmva{
			get { return _unidadAdmva; }
			set { _unidadAdmva = value; }
		}

		/// <summary>
		/// Acceder a la propiedad Usuario
		/// </summary>
		public string Usuario{
			get { return _usuario; }
			set { _usuario = value; }
		}
        /// <summary>
        /// 
        /// </summary>
        public FondosModel Fondo
        {
            get { return _fondo; }
            set { _fondo = value; }
        }

        public SubFondosModel SubFondo
        {
            get { return _subfondo; }
            set { _subfondo = value; }
        }
	}//end UsuariosModel

}//end namespace Modelos