///////////////////////////////////////////////////////////
//  CajasController.cs
//  Implementation of the Class CajasController
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:30
//  Original author: Elizabeth
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace SiCGA.Clases.Controladores {
	public class CajasController : Metodos {

		public CajasController(){

		}

		~CajasController(){

		}

		/// 
		/// <param name="o"></param>
		public override bool ConsultarRegistro(object o){

			return false;
		}

		/// 
		/// <param name="o"></param>
		public override bool ActualizarRegistro(object o){

			return false;
		}

		/// 
		/// <param name="o"></param>
		public override bool IngresarRegisto(object o){

			return false;
		}

		public override bool ConsultarRegistros(){

			return false;
		}

	}//end CajasController

}//end namespace Controladores