///////////////////////////////////////////////////////////
//  ClasificacionesController.cs
//  Implementation of the Class ClasificacionesController
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:30
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SiCGA.Clases.Modelos;



using SiCGA.Clases;
namespace SiCGA.Clases.Controladores {
	/// <summary>
	/// Controlador para la el Modelo Clasificaciones
	/// </summary>
	public class ClasificacionesController : Metodos {

		public ClasificacionesController(){

		}

		~ClasificacionesController(){

		}

		/// <summary>
		/// Método Para Consultar un Registro
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo class</param>
		public override bool ConsultarRegistro(Object o){

			if(o.GetType()==typeof(ClasificacionesModel))// Validar que el Objeto sea del Modelo ClasificacionesModel
            {
                var c = (ClasificacionesModel)o;// Castear la variable "c" al tipo ClasificacionesModel

                if(Abrir())// Intentar Abrir la Conexión
                {
                    //
                }
                else
                { return false; }// Error al intentar abrir la conexión, consultar Error
            }
            else
            { return false; }// No es del miismo tipo
		}

		/// <summary>
		/// Método Para Actualizar los Registros
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo class</param>
		public override bool ActualizarRegistro(Object o){

			return false;
		}

		/// <summary>
		/// Método para Ingresar un Registro
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo Class</param>
		public override bool IngresarRegisto(Object o){

			return false;
		}

		/// <summary>
		/// Método para Consultar Todos los Registros
		/// </summary>
		/// <returns>Boleano</returns>
		public override bool ConsultarRegistros(){

			return false;
		}

	}//end ClasificacionesController

}//end namespace Controladores