///////////////////////////////////////////////////////////
//  ContenidoCajasController.cs
//  Implementation of the Class ContenidoCajasController
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:32
//  Original author: Elizabeth
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SiCGA.Clases;
namespace SiCGA.SiCGA.Clases.Controladores {
	public class ContenidoCajasController : Metodos {

		public ContenidoCajasController(){

		}

		~ContenidoCajasController(){

		}

		/// 
		/// <param name="o"></param>
		public override bool ConsultarRegistro(object o){

			return false;
		}

		/// 
		/// <param name="o"></param>
		public override bool ActualizarRegistro(object o){

			return false;
		}

		/// 
		/// <param name="o"></param>
		public override bool IngresarRegisto(object o){

			return false;
		}

		public override bool ConsultarRegistros(){

			return false;
		}

	}//end ContenidoCajasController

}//end namespace Controladores