///////////////////////////////////////////////////////////
//  RegistrosController.cs
//  Implementation of the Class RegistrosController
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:18:49
//  Original author: Ing. Alan Ortiz Pèrez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SiCGA.Clases;
namespace SiCGA.Clases.Controladores {
	/// <summary>
	/// Controlador del Modelo Registros
	/// </summary>
	public class RegistrosController : Metodos {

		public RegistrosController(){

		}

		~RegistrosController(){

		}

		/// 
		/// <param name="o"></param>
		public override bool ConsultarRegistro(object o){

			return false;
		}

		/// 
		/// <param name="o"></param>
		public override bool ActualizarRegistro(object o){

			return false;
		}

		/// 
		/// <param name="o"></param>
		public override bool IngresarRegisto(object o){

			return false;
		}

		public override bool ConsultarRegistros(){

			return false;
		}

	}//end RegistrosController

}//end namespace Controladores