///////////////////////////////////////////////////////////
//  UsuariosController.cs
//  Implementation of the Class UsuariosController
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:19:09
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SiCGA.Clases.Modelos;


namespace SiCGA.Clases.Controladores {
	/// <summary>
	/// Controlador del Modelo Usuarios
	/// </summary>
	public class UsuariosController : Metodos {

		public UsuariosController(){

		}

		~UsuariosController(){

		}

		/// 
		/// <param name="o"></param>
		public override bool ActualizarRegistro(object o){

			return false;
		}

		/// <summary>
		/// Consultar un Usuario del Sistema
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del tipo Usuario</param>
		public override bool ConsultarRegistro(object o){

            if (o.GetType() == typeof(UsuariosModel))
            {
                var u = (UsuariosModel)o;
                if (Abrir())
                {
                    try
                    {
                        List<Parametros> lista = new List<Parametros>();
                        lista.Add(new Parametros(@"opc", "4"));
                        lista.Add(new Parametros(@"id", u.Id.ToString()));
                        lista.Add(new Parametros(@"usr", string.Empty));
                        lista.Add(new Parametros(@"pwd", string.Empty));
                        lista.Add(new Parametros(@"nom", string.Empty));
                        lista.Add(new Parametros(@"pat", string.Empty));
                        lista.Add(new Parametros(@"mat", string.Empty));
                        lista.Add(new Parametros(@"fondo", string.Empty));
                        lista.Add(new Parametros(@"subf", string.Empty));
                        lista.Add(new Parametros(@"unidad", string.Empty));
                        lista.Add(new Parametros(@"jera", string.Empty));
                        lista.Add(new Parametros(@"est", string.Empty));

                        string proce = "sp_usuarios_crud";

                        if (ConsultarProcedimiento(proce, lista))
                        {
                            return true;
                        }
                        else
                        { return false; }
                    }
                    catch(Exception e)
                    {
                        Error = e.Message.ToString();
                        return false;
                    }
                    finally { Cerrar(); }
                }
                else
                { return false; }
            }
            else
            { return false; }
		}

		public override bool ConsultarRegistros(){

			return false;
		}

		/// <summary>
		/// Ingresar un Usuario al Sistema
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto de tipo Usuario</param>
		public override bool IngresarRegisto(object o){

			return false;
		}

	}//end UsuariosController

}//end namespace Controladores