///////////////////////////////////////////////////////////
//  ValoresDoctalesController.cs
//  Implementation of the Class ValoresDoctalesController
//  Generated by Enterprise Architect
//  Created on:      10-mar.-2017 13:19:12
//  Original author: Ing. Alan Adalberto Ortiz Pérez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using SiCGA.Clases;
namespace SiCGA.Clases.Controladores {
	/// <summary>
	/// Controlador para el Modelo ValoresDoctales
	/// </summary>
	public class ValoresDoctalesController : Metodos {
        /// <summary>
        /// Constructor modificado por Rafa Matuz, Eseeee
        /// </summary>
		public ValoresDoctalesController(){

		}

		~ValoresDoctalesController(){

		}

		/// <summary>
		/// Método Para Consultar un Registro
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo class</param>
		public override bool ConsultarRegistro(Object o){

			return false;
		}

		/// <summary>
		/// Método Para Actualizar los Registros
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo class</param>
		public override bool ActualizarRegistro(Object o){

			return false;
		}

		/// <summary>
		/// Método para Ingresar un Registro
		/// </summary>
		/// <returns>Boleano</returns>
		/// <param name="o">Objeto del Tipo Class</param>
		public override bool IngresarRegisto(Object o){

			return false;
		}

		/// <summary>
		/// Método para Consultar Todos los Registros
		/// </summary>
		/// <returns>Boleano</returns>
		public override bool ConsultarRegistros(){

			return false;
		}

	}//end ValoresDoctalesController

}//end namespace Controladores